name = "sample-d1"
main = "src/index.tsx"
compatibility_date = "2022-12-31"

[[ d1_databases ]]
binding = "DB"
database_name = "sample-d1"
database_id = "f262ea72-83c8-4866-a61d-170af6dedd9e"
preview_database_id = "2e059acd-70b5-4ade-b1a3-54ee1d9f1124"
